from looper_through_Dolchs import looper_through_dolchs
one_specified_language_dolch_object='English'
returned_object = looper_through_dolchs(one_specified_language_dolch_object)
print(returned_object)
